import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./UserContext";



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html className="bg-[#fff]" lang="en">
//       <body clas className={inter.className}>{children}</body>
//     </html>
//   );
// }



export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html className="bg-[#fff]" lang="en">
        <body clas className={inter.className}>{children}</body>
      </html>
    </UserProvider>
  );
}